openapi: 3.0.0

info:
    title: Microsoft Intune via Graph API Plugin
    description: Skills for retrieving data from Microsoft Intune via Graph API calls
    version: "v1"
servers:
    - url: https://graph.microsoft.com/beta/deviceManagement


paths:
    /deviceConfigurations?$select=id,displayName,lastModifiedDateTime,roleScopeTagIds,microsoft.graph.unsupportedDeviceConfiguration/originalEntityTypeName&$expand=deviceStatusOverview,assignments&$top=120&$filter=isof(%27microsoft.graph.windowsUpdateForBusinessConfiguration%27)&$count=true:
        get:
            operationId: GetDeviceDeploymentStatus
            description: Get the Device Deployment Status in Intune per each Update Ring Profile by using a Microsoft Graph API call. 
              The response includes the number of device according to the deployment status of pending, not applicable, success, error, failed, conflict.
            ExamplePrompt:
              - 'Show me the device deployment status per update ring'
              - 'Give me the number of devices that failed to deploy on the update ring XYZ'
              - 'Give me the number of devices on which the deployment on the update ring XYZ returned an error'
            parameters:
            responses:
                "200":
                    description: OK
                    content:
                        application/json:

    /reports/getAppsInstallSummaryReport:
        post:
            operationId: GetAppsInstallStatusReport
            summary: Get Apps Install Status Report
            description: Retrieves the status report of apps installed on devices managed by Intune.
                The report lists the application deployment status for each app, including the install failure percentage, 
                along with the counts of install success, failures for deployments targeting on devices and user.
                It is possible to ask for any of these fields to be included in the report and / or to be used for filtering the results.
                "ApplicationId,"DisplayName","Publisher","Platform","Platform_loc","AppVersion","InstalledDeviceCount","InstalledUserCount",
                "FailedDeviceCount","FailedUserCount","PendingInstallDeviceCount","PendingInstallUserCount","NotApplicableDeviceCount","NotApplicableUserCount",
                "NotInstalledDeviceCount","NotInstalledUserCount","FailedDevicePercentage","AppPlatform". 
            ExamplePrompt:
              - 'List me the apps that have a install status failure rate on my managed devices between 75% and 100%'

            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                select:
                                    type: array
                                    items:
                                        type: string
                                    example: ["DisplayName","Publisher","Platform","AppVersion","FailedDevicePercentage","FailedDeviceCount","FailedUserCount","InstalledDeviceCount","InstalledUserCount","PendingInstallDeviceCount","PendingInstallUserCount","NotApplicableDeviceCount","NotApplicableUserCount","NotInstalledDeviceCount","NotInstalledUserCount","ApplicationId"]
                                filter:
                                    type: string
                                    example: "(FailedDevicePercentage gt '75' and FailedDevicePercentage le '100')"
                                skip:
                                    type: integer
                                    example: 0
                                search:
                                    type: string
                                    example: ""
                                orderBy:
                                    type: array
                                    items:
                                        type: string
                                    example: ["DisplayName"]
                                top:
                                    type: integer
                                    example: 50
            responses:
                '200':
                    description: Successful response with the apps install summary report
                    content:
                        application/json:
                '401':
                    description: Unauthorized
                '403':
                    description: Forbidden - Insufficient permissions to access the resource
                '500':
                    description: Internal Server Error - An error occurred on the server
