openapi: 3.0.0

info:
    title: Microsoft Intune via Graph API Plugin
    description: Skills for retrieving data from Microsoft Intune via Graph API calls
    version: "v1"
servers:
    - url: https://graph.microsoft.com/beta/deviceManagement


paths:
    /deviceConfigurations?$select=id,displayName,lastModifiedDateTime,roleScopeTagIds,microsoft.graph.unsupportedDeviceConfiguration/originalEntityTypeName&$expand=deviceStatusOverview,assignments&$top=120&$filter=isof(%27microsoft.graph.windowsUpdateForBusinessConfiguration%27)&$count=true:
        get:
            operationId: GetDeviceDeploymentStatus
            description: Get the Device Deployment Status in Intune per each Update Ring Profile by using a Microsoft Graph API call. 
              The response includes the number of device according to the deployment status of pending, not applicable, success, error, failed, conflict.
            ExamplePrompt:
              - 'Show me the device deployment status per update ring'
              - 'Give me the number of devices that failed to deploy on the update ring XYZ'
              - 'Give me the number of devices on which the deployment on the update ring XYZ returned an error'
            parameters:
            responses:
                "200":
                    description: OK
                    content:
                        application/json:

    /reports/getAppsInstallSummaryReport:
        post:
            operationId: GetAppsInstallStatusReport
            summary: Get Apps Install Status Report
            description: Retrieves the status report of apps installed on devices managed by Intune.
                The report lists the application deployment status for each app, including the install failure percentage, 
                along with the counts of install success, failures for deployments targeting on devices and user.

                When it is requested to return specific columns, create an array of strings with the internal name of the requested columns 
                and pass it to the 'select' input parameter. 
                For example, the request to retrieve the status of the installations for the apps and to return only the display name and publisher 
                of these apps implies the need to set the input parameter select equal to ["DisplayName","Publisher"].
                
                When it is requested to filter the results on the percentage or on the number of failures or success, create an OData filtering expression 
                with the internal name of the column to be used for filtering and pass it to the 'filter' input parameter. 
                For example, the request to retrieve the list of apps with install failure rate grater than 75% implies the need to set the input parameter 
                filter equal to (FailedDevicePercentage gt '75') for the API call. 
                
                When it is requested to return the status report only for a specific app, pass its name as string to the search parameter. 
                For example, the reuqets to retrieve the install status report for the app XYZ implies the need to set the input parameter search to "XYZ".   
                
                When it is requested to return the status report ordered by a specific set of columns, create an array of strings with the internal name of the 
                columns requested for sorting and pass it to the 'orderBy' input parameter. 
                For example, the reuqets to retrieve the install status report for the apps ordered by DisplayName implies the need to set the input parameter 
                orderBy equal to ["DisplayName"].   

                The internal name of the columns to be used in the select, filter and orderBy input parameters are 
                "ApplicationId,"DisplayName","Publisher","Platform","Platform_loc","AppVersion","InstalledDeviceCount","InstalledUserCount",
                "FailedDeviceCount","FailedUserCount","PendingInstallDeviceCount","PendingInstallUserCount","NotApplicableDeviceCount","NotApplicableUserCount",
                "NotInstalledDeviceCount","NotInstalledUserCount","FailedDevicePercentage","AppPlatform". 
                When creating the values or the expressions for the select, filter and orderBy input parameters, select from the above list the internal name more 
                assonant to the name specified by the user in the input prompt.

            ExamplePrompt:
              - 'List the apps that have a install status failure rate on my managed devices between 75% and 100%'
              - '/GetAppsInstallStatusReport Filter the apps with install failure rate greater than 5%'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                select:
                                    type: array
                                    description: An array of strings with the name of the fields to be included in the response. Always specify a value for this parameter. Use ["DisplayName"] if no other value is specified as input                                    
                                    items:
                                        type: string
                                    defaultValue: ["DisplayName"] 
                                    example: ["DisplayName","Publisher","Platform","AppVersion","FailedDevicePercentage","FailedDeviceCount","FailedUserCount","InstalledDeviceCount","InstalledUserCount","PendingInstallDeviceCount","PendingInstallUserCount","NotApplicableDeviceCount","NotApplicableUserCount","NotInstalledDeviceCount","NotInstalledUserCount","ApplicationId"]
                                filter:
                                    description: An OData filtering expression to be used for filtering the results in the response.
                                    type: string
                                    example: "(FailedDevicePercentage gt '75' and FailedDevicePercentage le '100')"
                                skip:
                                    type: integer
                                    example: 0
                                search:
                                    type: string
                                    example: ""
                                orderBy:
                                    type: array
                                    description: An array of strings with the name of the fields to be used for ordering the response.
                                    items:
                                        type: string
                                    example: ["DisplayName"]
                                top:
                                    type: integer
                                    example: 50
            responses:
                '200':
                    description: Successful response with the apps install summary report
                    content:
                        application/json:
                '401':
                    description: Unauthorized
                '403':
                    description: Forbidden - Insufficient permissions to access the resource
                '500':
                    description: Internal Server Error - An error occurred on the server
