openapi: 3.0.0

info:
    title: CISO Incidents Summary API Helper
    description: Helper skills used to get specific summary info on the incidents in Defender
    version: "0.0.1"

paths:
    /aaa:
        get: 
            operationId: CisoGetUsersStatus
            summary: Get the status of a list of users in terms of enablement, risk level in Entra and insider risk level in Purview 
            parameters:
                - in: query
                  name: users_upn 
                  schema:
                    type: string
                  required: true
                  description: Comma separated list of the User Principal Names (UPNs) of the user to be analyzed 
            responses:
                200:
                    description: Successful. 
                401:
                    description: Unsuccessful authentication.
