openapi: 3.0.0

info:
    title: GitHub Advanced Security for Azure DevOps - Alerts API
    description: Skills to retrieve Code Scanning, Dependabot Scanning and Secret Scanning alerts for the default (main) branch of
        the repositories (repos) of the projects stored in a specified Azure DevOps organization. 
        These scannings are executed by GitHub Advanced Security for Azure DevOps (a.k.a. GAzDO). 
        Despite its name suggesting a GitHub DevOps environment, GitHub Advanced Security for Azure DevOps is a security solution that 
        operates solely within Azure DevOps environments. It does not analyze code stored in GitHub repositories. The solution for GitHub 
        repositories is called “GitHub Advanced Security” or GhAS. DO NOT CONSIDER THESE SKILLS FOR PROMPTS RELATED TO GitHub REPOS.
        GitHub Advanced Security for Azure DevOps conducts secret scanning, dependency scanning (Dependabot, SCA), and code scanning 
        (via CodeQL, a SAST solution) in the Azure DevOps repositories where it is activated.
        GAzDO is billed monthly per "active committer". Committers are considered active if they have committed code to the repository 
        within the last 90 days. 
    version: "0.0.1"

paths:
    /_apis/management/enablement?api-version=7.2-preview.1:
        get: 
            operationId: ADO-Org-Enablement
            summary: Get the current status (configuration) of Advanced Security (GAzDO) for each repo of each project in the organization.
                This method returns configuration details for each repo of each project in the Azure DevOps organization. 
                Specifically, the output advSecEnabled specifies if Advanced Security (then CodeQL) is enabled. 
                Similarly, the output dependabotEnabled specifies if Dependabot (code analysis) is enabled.
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /_apis/management/meterusage/default?api-version=7.2-preview.1:
        get: 
            operationId: ADO-Org-Usage
            summary: Get active commiters at the entire Azure DevOps organizational level.
                This number is used when calculating billing information for 
                GitHub Advanced Security for Azure DevOps (GAzDO).
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /_apis/management/meterUsageEstimate?api-version=7.2-preview.1:
        get: 
            operationId: ADO-Org-Usage-Estimation
            summary: Estimate the active committers that would be added to the customer's usage 
                if Advanced Security was enabled for this organization.
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /{project}/_apis/management/enablement?api-version=7.2-preview.1:
        get: 
            operationId: ADO-Project-Enablement
            summary: Get the current status (configuration) of Advanced Security (GAzDO) for each repo of a specific project in the organization.
                This method returns configuration details for each repo of the specified project in the Azure DevOps organization. 
            parameters:
                - in: path
                  name: project 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /{project}/_apis/management/meterUsageEstimate?api-version=7.2-preview.1:
        get: 
            operationId: ADO-Project-Estimation
            summary: Estimate the number of active committers that would be added to the customer's usage 
                if Advanced Security was enabled for this project.
            parameters:
                - in: path
                  name: project 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /{project}/_apis/management/repositories/{repository}/enablement?api-version=7.2-preview.1:
        get: 
            operationId: ADO-Repo-Enablement
            summary: Get the current status (configuration) of Advanced Security (GAzDO) for a specific repo in a specific project in the organization.
                This method returns configuration details for each repo of the specified project in the Azure DevOps organization. 
                Specifically, the output advSecEnabled specifies if Advanced Security (then CodeQL) is enabled. 
                Similarly, the output dependabotEnabled specifies if Dependabot (code analysis) is enabled.
            parameters:
                - in: path
                  name: project 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repository 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
   /{project}/_apis/management/repositories/{repository}/meterUsageEstimate?api-version=7.2-preview.1:
        get: 
            operationId: ADO-Repo-Estimation
            summary: Estimate the committers that would be added to the customer's usage if Advanced Security was enabled for this repository.
            parameters:
                - in: path
                  name: project 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repository 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.