openapi: 3.0.0

info:
    title: GitHub Advanced Security Code Scanning
    description: Skills to retrieve code scanning default settings and code scanning alerts for the default branch for all eligible repositories (repos) in an organization. 
        These code scanning are executed by GitHub Advanced Security (GhAS).
    version: "0.0.1"

paths:
    /{repo}/code-scanning/alerts:
        get: 
            operationId: ListCodeScanningAlertsForARepository
            summary: Lists the alerts produced as result of the code scanning executed by GitHub Advanced Security (GhAS) 
                This provides details of the most recent instance of this alert for the default branch.
                The tool field in the response is the name of the code scanning tool that raised the alert.
            parameters:
                - in: header
                  name: User-Agent 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /{REPO}/code-scanning/alerts/{alert_num}:
        get: 
            operationId: GetCodeScanningAlert
            summary: Gets a single code scanning alert. 
            parameters:
                - in: header
                  name: User-Agent 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: alert_num 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.                    
    /{REPO}/code-scanning/alerts/{alert_num}/instances:
        get: 
            operationId: GetCodeScanningAlertInstances
            summary: Lists all instances of the specified code scanning alert. 
            parameters:
                - in: header
                  name: User-Agent 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: alert_num 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /{repo}/code-scanning/default-setup:
        get: 
            operationId: GetCodeScanningDefaultSetupConfigForRepo
            summary: Gets a code scanning default setup configuration for a specified GitHub repo
            parameters:
                - in: header
                  name: User-Agent 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
