openapi: 3.0.0

info:
    title: GitHub Advanced Security Code Scanning
    description: Skills to retrieve code scanning default settings and code scanning alerts for the default branch for all eligible repositories (repos) in an organization. 
        These code scanning are executed by GitHub Advanced Security (GhAS).
    version: "0.0.1"

paths:
    /{repo}/code-scanning/alerts:
        get: 
            operationId: ListCodeScanningAlertsForARepository
            summary: Lists the alerts produced as result of the code scanning executed by GitHub Advanced Security (GhAS) 
                Each alert is related to a specific code vulnerability found in one or more files in the repo.
                In each alert listed in the response, the field named "tool" contains the name of the code scanning tool that raised the alert.
                The field "most_recent_instance" contains the location (path, start line & column, end line & column) of the most recent instance of this alert in the default branch.
                The field "rule" contains the logic that found the code vulnerability and triggered the alert; the most relevant attributes for this rule are its "description" and its "severity".
            parameters:
                - in: header
                  name: User-Agent 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /{repo}/code-scanning/alerts/{alertnumber}:
        get: 
            operationId: GetCodeScanningAlert
            summary: Gets a single code scanning alert. 
            parameters:
                - in: header
                  name: User-Agent 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: alertnumber 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.                    
    /{repo}/code-scanning/alerts/{alertnumber}/instances:
        get: 
            operationId: GetCodeScanningAlertInstances
            summary: Lists all instances of the specified code scanning alert. 
            parameters:
                - in: header
                  name: User-Agent 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: alertnumber 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /{repo}/code-scanning/default-setup:
        get: 
            operationId: GetCodeScanningDefaultSetupConfigForRepo
            summary: Gets a code scanning default setup configuration for a specified GitHub repo
            parameters:
                - in: header
                  name: User-Agent 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
