openapi: 3.0.0

info:
    title: GitHub Advanced Security Code Scanning
    description: Skills to retrieve code scanning default settings and code scanning alerts for the default branch for all eligible repositories (repos) in an organization. Eligible repositories are repositories that are owned by organizations that you own or for which you are a security manager.
    version: "0.0.1"

paths:
    /{repo}/code-scanning/alerts:
        get: 
            operationId: ListCodeScanningAlertsForARepository
            summary: Lists code scanning alerts. The response includes a most_recent_instance object. This provides details of the most recent instance of this alert for the default branch (or for the specified Git reference if you used ref in the request).
            parameters:
                - in: header
                  name: User-Agent 
                  schema:
                    type: string
                  required: false
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
    /{REPO}/code-scanning/alerts/{alert_num}:
        get: 
            operationId: GetCodeScanningAlert
            summary: Gets a single code scanning alert. 
            parameters:
                - in: path
                  name: User-Agent 
                  schema:
                    type: string
                  required: false
                - in: path
                  name: repo 
                  schema:
                    type: string
                  required: true
                - in: path
                  name: alert_num 
                  schema:
                    type: int
                  required: true
            responses:
                200:
                    description: Successful authentication. 
                401:
                    description: Unsuccessful authentication.
